// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYevqnLcRCyq1iiLe4VqnCSuSarsMBXoY',
    appId: '1:842963059984:web:695d8c25772785d48fd195',
    messagingSenderId: '842963059984',
    projectId: 'deliveryapp-90007',
    authDomain: 'deliveryapp-90007.firebaseapp.com',
    storageBucket: 'deliveryapp-90007.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCed0a8GSy8p1hImqFCmfzuh_LTFoww4nU',
    appId: '1:842963059984:android:2b1012a7d440c9ba8fd195',
    messagingSenderId: '842963059984',
    projectId: 'deliveryapp-90007',
    storageBucket: 'deliveryapp-90007.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYevqnLcRCyq1iiLe4VqnCSuSarsMBXoY',
    appId: '1:842963059984:web:2b5644205ff60e378fd195',
    messagingSenderId: '842963059984',
    projectId: 'deliveryapp-90007',
    authDomain: 'deliveryapp-90007.firebaseapp.com',
    storageBucket: 'deliveryapp-90007.firebasestorage.app',
  );
}
